language: c
before_install:
    - sudo apt-get install -y valgrind
script:
    - cd Debug
    - make clean
    - make
    - valgrind --log-fd=1 ./Base 
    - valgrind --log-file=leak.out ./Base 
    - grep "All heap blocks were freed" leak.out

